on:
  schedule:
    - cron:  '0 5 * * *' # every day at midnight
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload FBref data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.
          
      - name: Install packages
        run: |
          R -e "install.packages(c('devtools', 'tidyverse', 'plotly', 'rvest', 'xml2', 'worldfootballR', 'aws.s3', 'rlang', 'data.table', 'shinythemes', 'shiny', 'shinydashboard', 'shinyjs', 'DT', 'feather', 'secret', 'rsconnect', 'stringr', 'kableExtra'), repos = 'https://cran.rstudio.com/')"
          R -e "devtools::install_github('yihui/knitr')"
               
      - name: Execute R Script
        env:
            access_key: ${{ secrets.ACCESS_KEY }}
            secret_key: ${{ secrets.SECRET_KEY }}
            aws_region: ${{ secrets.REGION }}
            bucket_name: ${{secrets.BUCKET_NAME}}
            
            shiny_acc: ${{secrets.SHINY_ACC_NAME}}
            shiny_secret: ${{secrets.SHINY_SECRET_TOKEN}}
            shiny_token: ${{secrets.SHINY_TOKEN}}
        run: |
            Rscript Collect\ Data/Update\ Data/Refresh\ Data\ Pull.R
            Rscript deploy.R
          
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: README.qmd
          
      
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
