on:
  schedule:
    - cron:  '0 0 * * *' # every day at midnight
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload FBref data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
              any::tidyverse
              any::plotly
              any::knitr
              any::kableExtra
              any::rvest
              any::xml2
              any::worldfootballR
              any::googledrive
              any::googleAuthR
              any::tictoc
              any::aws.s3
              any::rlang
              any::data.table
              any::shinythemes
              any::shiny
              any::shinydashboard
              any::shinyjs
              any::DT
              any::feather
              any::secret
               
      - name: Retrieve secrets
        run: |
          echo 'access_key <- "${{ secrets.ACCESS_KEY }}"' > secrets.R
          echo 'secret_key <- "${{ secrets.SECRET_KEY }}"' >> secrets.R
          echo 'aws_region <- "${{ secrets.REGION }}"' >> secrets.R
          echo 'bucket_name <- "${{ secrets.BUCKET_NAME }}"' >> secrets.R
      - name: Execute R Script
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        run: |
            source("secrets.R")
            # Your R script that requires AWS access
            Sys.setenv("AWS_ACCESS_KEY_ID" = access_key,
                       "AWS_SECRET_ACCESS_KEY" = secret_key,
                       "AWS_DEFAULT_REGION" = aws_region)
            Rscript Collect\ Data/Update\ Data/Refresh\ Data\ Pull.R
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
