on:
  schedule:
    - cron:  '0 0 * * *' # every day at midnight
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload FBref data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
              any::tidyverse
              any::plotly
              any::knitr
              any::kableExtra
              any::rvest
              any::xml2
              any::worldfootballR
              any::googledrive
              any::googleAuthR
              any::tictoc
              any::aws.s3
              any::rlang
              any::data.table
              any::shinythemes
              any::shiny
              any::shinydashboard
              any::shinyjs
              any::DT
              any::feather
              any::secret
               
      - name: Retrieve secrets
        run: |
          echo '${{ secrets.ACCESS_KEY }}' > secrets.R
          echo '${{ secrets.SECRET_KEY }}' >> secrets.R
          echo '${{ secrets.BUCKET_NAME }}' >> secrets.R
          echo '${{ secrets.REGION }}' >> secrets.R

      - name: Run R script
        run: |
          source('secrets.R')
          Sys.setenv('AWS_ACCESS_KEY_ID' = access_key,
                     'AWS_SECRET_ACCESS_KEY' = secret_key,
                     'AWS_DEFAULT_REGION' = aws_region)
          
          # Run R script with environment variables
          Rscript Collect\ Data/Update\ Data/Refresh\ Data\ Pull.R
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
