on:
  schedule:
    - cron:  '0 5 * * *' # every day at midnight
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload FBref data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
              devtools@2.4.4
              tidyverse@1.3.2
              any::maptools
              any::rgeos
              plotly@4.10.2
              any::rvest
              any::xml2
              worldfootballR@0.6.1
              aws.s3@0.3.20
              any::rlang
              any::data.table
              shinythemes@1.1
              any::shiny
              shinydashboard@0.7.1
              shinyjs@2.0.0
              DT@0.27
              feather@0.3.4
              any::secret
              rsconnect@1.0.1
              any::stringr
              any::kableExtra
              knitr@1.40
              ggsoccer@0.1.6
              any::curl
              shinyBS@0.20
              shinycssloaders@0.3
              flexdashboard@0.6.1

               
      - name: Execute R Script
        env:
            access_key: ${{ secrets.ACCESS_KEY }}
            secret_key: ${{ secrets.SECRET_KEY }}
            aws_region: ${{ secrets.REGION }}
            bucket_name: ${{secrets.BUCKET_NAME}}
            
            shiny_acc: ${{secrets.SHINY_ACC_NAME}}
            shiny_secret: ${{secrets.SHINY_SECRET_TOKEN}}
            shiny_token: ${{secrets.SHINY_TOKEN}}
        run: |
            Rscript Collect\ Data/Update\ Data/Refresh\ Data\ Pull.R
            Rscript deploy.R
          
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: README.qmd
          
      
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
